global change          ;( 1)
segment .data          ;( 2)
x  dd 4, 0, 0, 0, 0    ;( 3)
y  dq fun1, fun2, fun3 ;( 4)
segment .text          ;( 5)
change:                ;( 6)
  mov rax, [rdi]       ;( 7)
  mov rax, [rax-8]     ;( 8)
  mov [x+12], rax      ;( 9)
  sub dword[rdi+8], 1  ;(10)
  mov qword[rdi], y    ;(11)
  ret                  ;(12)
fun1:                  ;(13)
  mov edx, [rdi+8]     ;(14)
  jmp fun2             ;(15)
  ret                  ;(16)
fun2:                  ;(17)
  movsx rax, esi       ;(18)
  sub eax, edx         ;(19)
  cmovz eax, esi       ;(20)
  ret                  ;(21)
fun3:                  ;(22)
  mov r10, [rdi]       ;(23)
  call [r10]           ;(24)
  imul eax, eax        ;(25)
  ret                  ;(26)
;nasm -felf64 poly.asm -o poly.o && g++ -m64 -o poly1.o -c poly1.cpp && g++ -m64 poly1.o poly.o -o poly -no-pie
